'use client';

import {
  buildReachCertificateHtmlDataUrl,
  buildReachCertificateHtmlPdfUrl,
} from '@/lib/reach-certificate-download';
import { applyReachDocxPreviewStyles } from '@/lib/reach-docx-preview-styles';
import type { ReachCertificateHtmlData } from '@/lib/reach-certificate-html-data';
import type { TccCertificateHtmlData } from '@/lib/tcc-certificate-html-data';
import {
  downloadReachHtmlCertificatePdf,
  downloadReachHtmlCertificatePdfFromElement,
} from '@/lib/reach-certificate-html-pdf-client';
import { renderAsync } from 'docx-preview';
import '@/components/reach-certificate-fonts.css';
import '@/components/reach-certificate-a4.css';
import { REACH_CERT_A4_WIDTH_PX } from '@/lib/reach-certificate-a4';

const DOCX_PREVIEW_CLASS = 'docx';

const RC_PDF_SETUP_MESSAGE =
  'PDF download failed. Ensure the server has Puppeteer/Chromium installed.';

function triggerBlobDownload(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  window.open(url, '_blank', 'noopener,noreferrer');
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = fileName;
  anchor.style.display = 'none';
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

function findDocxWrapper(host: HTMLElement): HTMLElement | null {
  return (
    host.querySelector('.docx-preview-wrapper') ??
    host.querySelector(`.${DOCX_PREVIEW_CLASS}-wrapper`) ??
    host.querySelector('.docx-wrapper')
  );
}

function waitForLayout(): Promise<void> {
  return new Promise((resolve) => {
    window.requestAnimationFrame(() => {
      window.requestAnimationFrame(() => {
        window.setTimeout(resolve, 500);
      });
    });
  });
}

async function waitForFontsAndLayout(): Promise<void> {
  if (document.fonts?.ready) {
    await document.fonts.ready;
  }
  await waitForLayout();
}

function sanitizeDocxCloneForPdf(root: HTMLElement): void {
  root.querySelectorAll('*').forEach((node) => {
    if (!(node instanceof HTMLElement)) return;
    node.style.textDecoration = 'none';
    node.style.textDecorationLine = 'none';
    node.style.opacity = '1';
    node.style.visibility = 'visible';
    node.style.transform = 'none';
    node.style.clip = 'auto';
    node.style.backgroundClip = 'padding-box';
    node.style.boxDecorationBreak = 'clone';
  });

  root.querySelectorAll('table').forEach((table) => {
    if (!(table instanceof HTMLElement)) return;
    table.style.borderCollapse = 'collapse';
    table.style.borderSpacing = '0';
    table.style.width = '100%';
    table.style.tableLayout = 'auto'; // Let columns auto-resize to fit our constraints

    // Adjust colgroup columns if generated by docx-preview
    const cols = table.querySelectorAll('col');
    if (cols.length >= 2) {
      const col1 = cols[0] as HTMLElement;
      col1.setAttribute('width', '180');
      col1.style.width = '180px';
      col1.style.minWidth = '180px';

      const col2 = cols[1] as HTMLElement;
      col2.removeAttribute('width');
      col2.style.width = 'auto';
    }
  });

  root.querySelectorAll('td p, th p').forEach((p) => {
    if (p instanceof HTMLElement) {
      p.style.margin = '0';
      p.style.padding = '0';
    }
  });

  root.querySelectorAll('td, th').forEach((cell) => {
    if (!(cell instanceof HTMLElement)) return;
    cell.style.textDecoration = 'none';
    cell.style.borderCollapse = 'collapse';
    cell.style.verticalAlign = 'middle';
    
    // Prevent common table labels from wrapping and getting clipped
    const text = (cell.innerText || cell.textContent || '').trim().toLowerCase();
    const isLabel = 
      text.includes('substance name') ||
      text.includes('cas number') ||
      text.includes('ec number') ||
      text.includes('tonnage band') ||
      text.includes('registration number') ||
      text.includes('authorized holder') ||
      text.includes('authorized quantity') ||
      text.includes('date of issuance') ||
      text.includes('date of expiration') ||
      text.includes('cas no') ||
      text.includes('ec no') ||
      text.includes('tonnage');

    if (isLabel) {
      cell.style.whiteSpace = 'nowrap';
      cell.style.width = '180px';
      cell.style.minWidth = '180px';
      
      // Ensure inner paragraph/span elements also do not wrap and have no margins
      cell.querySelectorAll('p, span').forEach((inner) => {
        if (inner instanceof HTMLElement) {
          inner.style.whiteSpace = 'nowrap';
          inner.style.margin = '0';
          inner.style.padding = '0';
        }
      });
    }

    // Substance Name long text margin-top: -5px fix
    if (text === 'substance name') {
      const nextCell = cell.nextElementSibling;
      if (nextCell && nextCell instanceof HTMLElement) {
        const p = nextCell.querySelector('p');
        if (p) {
          const chemName = (p.innerText || p.textContent || '').trim();
          if (chemName.length >= 60) {
            p.style.marginTop = '-5px';
            p.style.marginBottom = '-2px';
            p.style.lineHeight = '1.1';
          }
        }
      }
    }
  });
}

async function convertDocxBlobToPdfAndDownload(blob: Blob, fileName: string): Promise<void> {
  const host = document.createElement('div');
  host.className = 'docx-preview-container';
  host.setAttribute('aria-hidden', 'true');
  host.style.cssText = [
    'position:fixed',
    'left:0',
    'top:0',
    `width:${REACH_CERT_A4_WIDTH_PX}px`,
    'background:#ffffff',
    'pointer-events:none',
    'clip:rect(0,0,0,0)',
    'overflow:visible',
    'z-index:-1',
  ].join(';');
  document.body.appendChild(host);

  try {
    await renderAsync(blob, host, host, {
      className: 'docx-preview',
      inWrapper: true,
      ignoreWidth: false,
      ignoreHeight: false,
      breakPages: true,
      renderHeaders: true,
      renderFooters: true,
    });

    await waitForLayout();

    const wrapper = findDocxWrapper(host);
    if (!wrapper) {
      throw new Error('Certificate preview failed to render.');
    }

    applyReachDocxPreviewStyles(wrapper);

    await waitForFontsAndLayout();

    const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
      import('html2canvas'),
      import('jspdf'),
    ]);

    const pageElements = Array.from(wrapper.children).filter(
      (el): el is HTMLElement => el instanceof HTMLElement && el.offsetHeight > 0
    );
    const targets = pageElements.length > 0 ? pageElements : [wrapper];

    const pdf = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const scale = Math.max(2, Math.min(3, window.devicePixelRatio || 2));

    for (let i = 0; i < targets.length; i++) {
      const canvas = await html2canvas(targets[i], {
        scale,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#ffffff',
        logging: false,
        scrollX: 0,
        scrollY: 0,
        width: targets[i].scrollWidth,
        height: targets[i].scrollHeight,
        onclone: (_doc, clonedElement) => {
          sanitizeDocxCloneForPdf(clonedElement);
        },
      });

      if (canvas.width === 0 || canvas.height === 0) {
        throw new Error('Certificate preview failed to render.');
      }

      const imgData = canvas.toDataURL('image/jpeg', 0.92);
      let imgWidth = pageWidth;
      let imgHeight = (canvas.height * imgWidth) / canvas.width;

      if (imgHeight > pageHeight) {
        imgHeight = pageHeight;
        imgWidth = (canvas.width * imgHeight) / canvas.height;
      }

      const x = (pageWidth - imgWidth) / 2;
      if (i > 0) pdf.addPage();
      pdf.addImage(imgData, 'JPEG', x, 0, imgWidth, imgHeight);
    }

    triggerBlobDownload(pdf.output('blob'), fileName);
  } finally {
    document.body.removeChild(host);
  }
}

function isDocxContentType(contentType: string) {
  return (
    contentType.includes('wordprocessingml') ||
    contentType.includes('officedocument') ||
    contentType.includes('application/vnd.openxmlformats')
  );
}

function isPdfContentType(contentType: string, bytes: Uint8Array) {
  return (
    contentType.includes('application/pdf') ||
    contentType.includes('application/octet-stream') ||
    (bytes.length >= 4 &&
      bytes[0] === 0x25 &&
      bytes[1] === 0x50 &&
      bytes[2] === 0x44 &&
      bytes[3] === 0x46)
  );
}

export type CertificateDownloadResult = {
  format: 'pdf';
  fileName: string;
};

function appendCacheBuster(url: string): string {
  const separator = url.includes('?') ? '&' : '?';
  return `${url}${separator}_=${Date.now()}`;
}

async function fetchDocxBlob(docxUrl: string): Promise<Blob> {
  const res = await fetch(appendCacheBuster(docxUrl), {
    credentials: docxUrl.startsWith('/') ? 'same-origin' : 'omit',
    cache: 'no-store',
  });
  if (!res.ok) {
    const body = (await res.json().catch(() => null)) as { error?: string } | null;
    throw new Error(body?.error || 'Failed to load certificate document.');
  }
  return res.blob();
}

async function downloadPdfFromDocxSources(
  docxUrls: string[],
  fileName: string
): Promise<CertificateDownloadResult> {
  let lastError: string | undefined;

  for (const docxUrl of docxUrls) {
    try {
      await convertDocxBlobToPdfAndDownload(await fetchDocxBlob(docxUrl), fileName);
      return { format: 'pdf', fileName };
    } catch (err) {
      if (err instanceof Error) {
        lastError = err.message;
      }
    }
  }

  throw new Error(lastError || 'Failed to generate certificate PDF.');
}

function extractCertificateIdFromUrl(url: string): string | null {
  try {
    const parsed = new URL(url, window.location.origin);
    return parsed.searchParams.get('certificateId');
  } catch {
    return null;
  }
}

async function downloadFromPdfResponse(
  res: Response,
  fileName: string
): Promise<CertificateDownloadResult | { kind: 'docx'; docxUrl: string } | { kind: 'unsupported' }> {
  const contentType = res.headers.get('Content-Type') || '';

  if (contentType.includes('application/json')) {
    const body = (await res.json()) as {
      downloadMode?: string;
      previewMode?: string;
      docxUrl?: string;
      error?: string;
    };

    if ((body.downloadMode === 'docx' || body.previewMode === 'docx') && body.docxUrl) {
      return { kind: 'docx', docxUrl: body.docxUrl };
    }

    throw new Error(body.error || 'Certificate download failed.');
  }

  const blob = await res.blob();
  const bytes = new Uint8Array(await blob.arrayBuffer());

  if (isPdfContentType(contentType, bytes)) {
    triggerBlobDownload(new Blob([bytes], { type: 'application/pdf' }), fileName);
    return { format: 'pdf', fileName };
  }

  if (isDocxContentType(contentType)) {
    await convertDocxBlobToPdfAndDownload(blob, fileName);
    return { format: 'pdf', fileName };
  }

  return { kind: 'unsupported' };
}

async function fetchReachHtmlDataForDownload(params: {
  pdfUrl: string;
  clientId?: string;
  chemicalId?: string;
  registrationNumber?: string;
  issuedDate?: string;
  validatedDate?: string;
  tonnageBand?: string | null;
}): Promise<ReachCertificateHtmlData> {
  const certificateId = extractCertificateIdFromUrl(params.pdfUrl);
  const url = buildReachCertificateHtmlDataUrl({
    certificateId: certificateId ?? undefined,
    clientId: params.clientId,
    chemicalId: params.chemicalId,
    registrationNumber: params.registrationNumber,
    issuedDate: params.issuedDate,
    validatedDate: params.validatedDate,
    tonnageBand: params.tonnageBand,
  });

  const res = await fetch(appendCacheBuster(url), {
    credentials: 'same-origin',
    cache: 'no-store',
  });

  if (!res.ok) {
    const body = (await res.json().catch(() => null)) as { error?: string } | null;
    throw new Error(body?.error || 'Failed to load certificate data for PDF.');
  }

  return (await res.json()) as ReachCertificateHtmlData;
}

async function downloadRcHtmlPreviewPdf(params: {
  fileName: string;
  htmlData?: ReachCertificateHtmlData | null;
  pdfUrl: string;
  clientId?: string;
  chemicalId?: string;
  registrationNumber?: string;
  issuedDate?: string;
  validatedDate?: string;
  tonnageBand?: string | null;
}): Promise<CertificateDownloadResult> {
  const certificateId = extractCertificateIdFromUrl(params.pdfUrl);
  const serverPdfUrl = buildReachCertificateHtmlPdfUrl({
    certificateId: certificateId ?? undefined,
    clientId: params.clientId,
    chemicalId: params.chemicalId,
    registrationNumber: params.registrationNumber,
    issuedDate: params.issuedDate,
    validatedDate: params.validatedDate,
    tonnageBand: params.tonnageBand,
  });

  try {
    const res = await fetch(appendCacheBuster(serverPdfUrl), {
      credentials: 'same-origin',
      cache: 'no-store',
    });
    if (res.ok) {
      const parsed = await downloadFromPdfResponse(res, params.fileName);
      if (!('kind' in parsed)) {
        return parsed;
      }
    } else {
      const body = (await res.json().catch(() => null)) as { error?: string } | null;
      throw new Error(body?.error || `Server PDF generation failed (${res.status}).`);
    }
  } catch (err) {
    if (err instanceof Error && !err.message.includes('Failed to fetch')) {
      throw err;
    }
    // Network failure only — fall through to client-side render
  }

  const onPage = document.querySelector('[data-reach-cert-root]');
  if (onPage instanceof HTMLElement) {
    await downloadReachHtmlCertificatePdfFromElement(onPage, params.fileName);
    return { format: 'pdf', fileName: params.fileName };
  }

  if (params.htmlData) {
    await downloadReachHtmlCertificatePdf(params.htmlData, params.fileName);
    return { format: 'pdf', fileName: params.fileName };
  }

  const htmlData = await fetchReachHtmlDataForDownload(params);
  await downloadReachHtmlCertificatePdf(htmlData, params.fileName);
  return { format: 'pdf', fileName: params.fileName };
}

export async function downloadCertificatePdf(params: {
  pdfUrl: string;
  docxUrl: string;
  fileName: string;
  previewDocxUrl?: string | null;
  officeDocxUrl?: string | null;
  certificateType?: 'rc' | 'tcc';
  htmlData?: ReachCertificateHtmlData | TccCertificateHtmlData | null;
  clientId?: string;
  chemicalId?: string;
  registrationNumber?: string;
  issuedDate?: string;
  validatedDate?: string;
  tonnageBand?: string | null;
}): Promise<CertificateDownloadResult> {
  const isRc = params.certificateType === 'rc';
  let serverError: string | undefined;

  if (isRc) {
    return downloadRcHtmlPreviewPdf({
      fileName: params.fileName,
      htmlData: params.htmlData as ReachCertificateHtmlData | null | undefined,
      pdfUrl: params.pdfUrl,
      clientId: params.clientId,
      chemicalId: params.chemicalId,
      registrationNumber: params.registrationNumber,
      issuedDate: params.issuedDate,
      validatedDate: params.validatedDate,
      tonnageBand: params.tonnageBand,
    });
  }

  if (params.certificateType === 'tcc') {
    try {
      const pdfRes = await fetch(appendCacheBuster(params.pdfUrl), {
        credentials: 'same-origin',
        cache: 'no-store',
      });

      if (pdfRes.ok) {
        const parsed = await downloadFromPdfResponse(pdfRes, params.fileName);
        if (!('kind' in parsed)) {
          return parsed;
        }
      } else {
        const body = (await pdfRes.json().catch(() => null)) as { error?: string } | null;
        serverError = body?.error;
      }
    } catch (err) {
      if (err instanceof Error && !serverError) {
        serverError = err.message;
      }
    }

    throw new Error(serverError || RC_PDF_SETUP_MESSAGE);
  }

  throw new Error('Certificate type is required for PDF download.');
}
